

spring:
  datasource:
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5436/reviews-db
    tomcat:
      validation-query: "SELECT 1"
      test-while-idle: true
  jpa:
    open-in-view: false
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        format_sql: true
    hibernate:
      ddl-auto: update
  application:
    name: reviews-service
  profiles:
    active: default
  graphql:
    graphiql:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-components: always
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    inc.evil: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters
server:
  port: 8082
