### GET all reviews
GET http://localhost:8070/api/v1/reviews/

### GET reviews by author
GET http://localhost:8070/api/v1/reviews/filter?author=mike

### GET reviews by course ID
GET http://localhost:8070/api/v1/reviews/filter?courseId=124

### GET reviews by creation date
GET http://localhost:8070/api/v1/reviews/filter?date={date}

### GET review by ID
GET http://localhost:8070/api/v1/reviews/34

### POST a new review
POST http://localhost:8070/api/v1/reviews/
Content-Type: application/json

{
  "text": "This is an amazing course!",
  "author": "Mike Scott",
  "authorTelephone": "555-1234",
  "authorEmail": "mikescott@example.com",
  "invoiceCode": "ABC123",
  "courseId": 124
}

### DELETE a review by ID
DELETE http://localhost:8070/api/v1/reviews/{id}
