version: '3'
services:
  reviews-operational-ds1:
    image: postgres:13.3
    container_name: reviews-operational-ds1
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: reviews-db
    ports:
      - "5435:5432"
  reviews-operational-ds2:
    image: postgres:13.3
    container_name: reviews-operational-ds2
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: reviews-db
    ports:
      - "5436:5432"
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

