version: '2'
services:
#  postgresql-master:
#    image: 'bitnami/postgresql:latest'
#    ports:
#      - '5432:5432'
#    volumes:
#      - 'postgresql_master_data:/bitnami/postgresql'
#    environment:
#      - POSTGRESQL_REPLICATION_MODE=master
#      - POSTGRESQL_REPLICATION_USER=repl_user
#      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
#      - POSTGRESQL_USERNAME=my_user
#      - POSTGRESQL_PASSWORD=my_password
#      - POSTGRESQL_DATABASE=reviews-db
#  postgresql-slave:
#    image: 'bitnami/postgresql:latest'
#    ports:
#      - '5432'
#    depends_on:
#      - postgresql-master
#    environment:
#      - POSTGRESQL_REPLICATION_MODE=slave
#      - POSTGRESQL_REPLICATION_USER=repl_user
#      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
#      - POSTGRESQL_MASTER_HOST=postgresql-master
#      - POSTGRESQL_USERNAME=my_user
#      - POSTGRESQL_PASSWORD=my_password
#      - POSTGRESQL_MASTER_PORT_NUMBER=5432
  mysql-master:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_master_data:/bitnami/mysql/data'
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=reviews-db
  mysql-slave:
    image: 'bitnami/mysql:latest'
    ports:
      - '3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
  zookeeper:
    image: zookeeper
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181
volumes:
  postgresql_master_data:
    driver: local
  mysql_master_data:
    driver: local


